### ISSUE TITLE
SlicerAutoscoperM page link does not work

### ISSUE THREAD

**Issue by bpaniagua** [BrownBiomechanics/autoscoperm.slicer.org#16]

**Comment by jcfr** [comment]
May there is an issue your browser cache ? 

The following links seems to all be working:
* Landing page
  * https://autoscoperm.slicer.org/
  * https://github.com/BrownBiomechanics/autoscoper
* About
  * [Team](https://autoscoperm.slicer.org/team/)
  * [Call for Collaboration](https://autoscoperm.slicer.org/call-for-collaboration/)
  * [License](https://autoscoper.readthedocs.io/en/latest/about.html#license)
  * [How to cite](https://autoscoper.readthedocs.io/en/latest/about.html#how-to-cite)
  * [Acknowledgments](https://autoscoperm.slicer.org/acknowledgments/)
* ASB 2023 Symposium
  * [Agenda](https://autoscoperm.slicer.org/events/2023/08/09/asb-2023-symposium.html#agenda)
  * [SlicerAutoscoperM web page](https://autoscoperm.slicer.org/)
  * [Documentation](https://autoscoperm.slicer.org/documentation/)

**Comment by jcfr** [comment]
Closing. This was fixed in https://github.com/BrownBiomechanics/autoscoperm.slicer.org/commit/14e36e0df7c81d54c9cf28644fe2cf5f52c1faea
